---
commonOverlays:
  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
    action: delete

yamlFiles:
  - name: "prometheus config"
    path: "../../vendor/"
    outputPath: "observability/prometheus/"
    overlays:
      - name: "ensure we are only acting upon config resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Secret")]
              - query: $[?($.kind != "ConfigMap")]

      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "{{ .namespace }}"

    # documents: # optional and only used for multi-doc yaml files
    #       # need to refer to their path by their index
    #       - name: the manifest that does something
    #       - path: 0
    #         query: $
    #         action: delete
    #       - path: 1
    #         query: $
    #         action: delete
    #       - path: 2
    #         query: $
    #         action: delete
    #       - path: 3
    #         query: $
    #         action: delete
    #       - path: 4
    #         query: $
    #         action: delete
    #       - path: 5
    #         query: $
    #         action: delete
    #       - path: 6
    #         query: $
    #         action: delete
    #       - path: 7
    #         query: $
    #         action: delete