---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-route53
  namespace: ingress-system
  labels:
    app.kubernetes.io/name: external-dns-route53
    app.kubernetes.io/instance: external-dns-route53
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: v0.12.2
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: platform-component-library
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
stringData:
  EXTERNAL_DNS_TXT_OWNER_ID: external-dns-
  EXTERNAL_DNS_TXT_PREFIX: external-dns-
  EXTERNAL_DNS_PROVIDER: aws
  EXTERNAL_DNS_AWS_ZONE_TYPE: private
  EXTERNAL_DNS_AWS_PREFER_CNAME: "true"
  EXTERNAL_DNS_DOMAIN_FILTER: mydomain.com
  EXTERNAL_DNS_POLICY: sync
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
