---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: v0.12.2
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: platform-component-library
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
  namespace: ingress-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: v0.12.2
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: platform-component-library
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: ingress-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: v0.12.2
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: platform-component-library
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
  namespace: ingress-system
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - watch
      - list
