---
commonOverlays:
  - name: "inject the platform purpose label"
    query: "$"
    action: merge
    value:
      metadata:
        labels:
          app: external-dns-google
          app.kubernetes.io/name: external-dns-google
          app.kubernetes.io/instance: external-dns
      spec:
        selector:
          matchLabels:
            app: external-dns-google
        template:
          metadata:
            labels:
              app: external-dns-google
              app.kubernetes.io/name: external-dns-google
              app.kubernetes.io/instance: external-dns
    documentQuery:
      - conditions:
          - query: $[?($.kind == "Deployment")]

  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "apply nukleros labels to pod template"
    query: "spec.template.metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "external-dns deployments"
    path: "../../vendor/external-dns-deployment.yaml"
    outputPath: "ingress/external-dns/deployment-google.yaml"
    overlays:
      - name: "update deployment spec"
        query: $
        value:
          metadata:
            name: "{{ .names.google }}"
            namespace: "{{ .namespace }}"
          spec:
            replicas: !!int {{ .replicas }}
            template:
              spec:
                securityContext:
                  fsGroup: 1001
                  runAsUser: 1001
                  runAsGroup: 1001
                  runAsNonRoot: true
                nodeSelector:
                  kubernetes.io/os: linux
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          topologyKey: kubernetes.io/hostname
                          labelSelector:
                            matchExpressions:
                              - key: app.kubernetes.io/name
                                operator: In
                                values:
                                  - "{{ .names.google }}"

      - name: "update container spec"
        query: spec.template.spec.containers[*]
        value:
          envFrom:
            - secretRef:
                name: external-dns-google
          image: "{{ .image }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "{{ .resources.requests.cpu }}"
              memory: "{{ .resources.requests.memory }}"
            limits:
              cpu: "{{ .resources.limits.cpu }}"
              memory: "{{ .resources.limits.memory }}"
