---
commonOverlays:
  - name: "add kubernetes and nukleros labels on deployments"
    query: "metadata"
    value:
      labels:
        app.kubernetes.io/version: {{ .version }}
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/managed-by: platform-component-library
        platform.nukleros.io/group: certificates
        platform.nukleros.io/project: cert-manager

  - name: "add kubernetes and nukleros labels on pods"
    query: "spec.template.metadata"
    value:
      labels:
        app.kubernetes.io/version: {{ .version }}
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/managed-by: platform-component-library
        platform.nukleros.io/group: certificates
        platform.nukleros.io/project: cert-manager

yamlFiles:
  - name: "cert-manager deployments"
    path: "../../vendor/cert-manager.yaml"
    outputPath: "certificates/cert-manager/deployment.yaml"
    overlays:
      - name: "ensure we are only acting upon deployment resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Deployment")]

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"

      - name: "ensure replicas are updated"
        query: spec.replicas
        value: !!int {{ .replicas }}

      - name: "ensure leader election namespace is updated"
        query: spec.template.spec.containers[*].args[?(@ =~ /^--leader-election-namespace/)]
        value: --leader-election-namespace=$(POD_NAMESPACE)

      - name: "ensure namespace for dns names is updated"
        query: spec.template.spec.containers[0].args[?(@ =~ /^--dynamic-serving-dns-names=/)]
        value: "--dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.$(POD_NAMESPACE),cert-manager-webhook.$(POD_NAMESPACE).svc"
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

      - name: "ensure pod security context is updated"
        query: spec.template.spec.securityContext
        action: replace
        value:
          fsGroup: 1001
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true

      - name: "ensure container security context is updated"
        query: spec.template.spec.containers[*].securityContext
        action: replace
        onMissing:
          action: inject
        value:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]

      - name: "ensure controller resources are updated"
        query: spec.template.spec.containers[*]
        value:
          resources:
            requests:
              cpu: "{{ .controller.resources.requests.cpu }}"
              memory: "{{ .controller.resources.requests.memory }}"
            limits:
              cpu: "{{ .controller.resources.limits.cpu }}"
              memory: "{{ .controller.resources.limits.memory }}"
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager")]

      - name: "set controller deployment labels"
        query: "metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/component: controller
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager")]

      - name: "set controller label selectors"
        query: "spec.selector"
        value:
          matchLabels:
            app.kubernetes.io/name: cert-manager
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/component: controller
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager")]

      - name: "set controller pod labels"
        query: "spec.template.metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/component: controller
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager")]

      - name: "ensure controller anti affinity is set"
        query: spec.template.spec
        action: merge
        value:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - cert-manager
          nodeSelector:
            kubernetes.io/os: linux
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager")]

      - name: "ensure injector resources are updated"
        query: spec.template.spec.containers[*]
        value:
          resources:
            requests:
              cpu: "{{ .injector.resources.requests.cpu }}"
              memory: "{{ .injector.resources.requests.memory }}"
            limits:
              cpu: "{{ .injector.resources.limits.cpu }}"
              memory: "{{ .injector.resources.limits.memory }}"
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-cainjector")]

      - name: "set injector deployment labels"
        query: "metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager-cainjector
            app.kubernetes.io/instance: cert-manager-cainjector
            app.kubernetes.io/component: cainjector
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-cainjector")]

      - name: "set injector label selectors"
        query: "spec.selector"
        value:
          matchLabels:
            app.kubernetes.io/name: cert-manager-cainjector
            app.kubernetes.io/instance: cert-manager-cainjector
            app.kubernetes.io/component: cainjector
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-cainjector")]

      - name: "set injector pod labels"
        query: "spec.template.metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager-cainjector
            app.kubernetes.io/instance: cert-manager-cainjector
            app.kubernetes.io/component: cainjector
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-cainjector")]

      - name: "ensure injector anti affinity is set"
        query: spec.template.spec
        action: merge
        value:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - cert-manager-cainjector
          nodeSelector:
            kubernetes.io/os: linux
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-cainjector")]

      - name: "ensure webhook resources are updated"
        query: spec.template.spec.containers[*]
        value:
          resources:
            requests:
              cpu: "{{ .webhook.resources.requests.cpu }}"
              memory: "{{ .webhook.resources.requests.memory }}"
            limits:
              cpu: "{{ .webhook.resources.limits.cpu }}"
              memory: "{{ .webhook.resources.limits.memory }}"
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

      - name: "set webhook deployment labels"
        query: "metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager-webhook
            app.kubernetes.io/instance: cert-manager-webhook
            app.kubernetes.io/component: webhook
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

      - name: "set webhook label selectors"
        query: "spec.selector"
        value:
          matchLabels:
            app.kubernetes.io/name: cert-manager-webhook
            app.kubernetes.io/instance: cert-manager-webhook
            app.kubernetes.io/component: webhook
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

      - name: "set webhook pod labels"
        query: "spec.template.metadata"
        value:
          labels:
            app.kubernetes.io/name: cert-manager-webhook
            app.kubernetes.io/instance: cert-manager-webhook
            app.kubernetes.io/component: webhook
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

      - name: "ensure webhook anti affinity is set"
        query: spec.template.spec
        action: merge
        value:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - cert-manager-webhook
          nodeSelector:
            kubernetes.io/os: linux
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "cert-manager-webhook")]

