---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "cert-manager services"
    path: "../../vendor/cert-manager.yaml"
    outputPath: "certificates/cert-manager/service.yaml"
    overlays:
      - name: "ensure we are only acting upon service resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Service")]

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"
