---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/group: "{{ .group }}"
      platform.nukleros.io/project: "{{ .project }}"
    # replace labels here to remove all of the helm info
    action: replace
    onMissing:
      action: inject

  - name: "remove helm annotations"
    query: "metadata.annotations"
    action: delete

  - name: "rename resources to remove duplication (e.g. reloader-reloader)"
    query:
      - "metadata.name"
      - "subjects[*].name"
      - "roleRef.name"
    value: "{{ .name }}"

yamlFiles:
  - name: "reloader rbac"
    path: "../../vendor/reloader.yaml"
    outputPath: "secrets/reloader/rbac.yaml"
    overlays:
      # TODO: this doesn't remove the namespace like it should.  although it will not affect
      #       functionality, it would be nice if this were consistent
      - name: "remove namespace from cluster-scoped resources"
        query: "metadata.namespace"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind == "ClusterRole")]
              - query: $[?($.kind == "ClusterRoleBinding")]

      - name: "ensure we are only acting upon rbac resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ServiceAccount")]
              - query: $[?($.kind != "Role")]
              - query: $[?($.kind != "RoleBinding")]
              - query: $[?($.kind != "ClusterRole")]
              - query: $[?($.kind != "ClusterRoleBinding")]

      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "{{ .namespace }}"
        onMissing:
          action: ignore
