---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.labels["heritage"]
      - metadata.labels["release"]
      - metadata.labels["chart"]
    action: delete

yamlFiles:
  - name: "openbao network policies"
    path: "../../vendor/openbao.yaml"
    outputPath: "secrets/openbao/networkpolicy.yaml"
    overlays:
      - name: "ensure we are only acting upon network policy resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "NetworkPolicy")]

      - name: "ensure namespace is set (the upstream chart's NetworkPolicy template omits this field entirely)"
        query: metadata
        action: merge
        value:
          namespace: "{{ .namespace }}"
