---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.labels["heritage"]
      - metadata.labels["release"]
      - metadata.labels["chart"]
    action: delete

yamlFiles:
  - name: "openbao injector webhook"
    path: "../../vendor/openbao.yaml"
    outputPath: "secrets/openbao/webhook.yaml"
    overlays:
      - name: "ensure we are only acting upon mutatingwebhookconfiguration resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "MutatingWebhookConfiguration")]

      - name: "ensure the webhook's backing service reference uses the correct namespace"
        query: webhooks[*].clientConfig.service.namespace
        value: "{{ .namespace }}"
