---
project: infisical
server:
  replicas: 2
  resources:
    requests:
      cpu: "350m"
      memory: "1000Mi"
    limits:
      cpu: "350m"
      memory: "1000Mi"
redis:
  replicas: 1  # do not change
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "750m"
      memory: "768Mi"
postgres:
  replicas: 1  # do not change
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "750m"
      memory: "768Mi"
