---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "infisical bootstrap admin credentials"
    path: "../../static/config-initial-admin.yaml"
    outputPath: "secrets/infisical/config-initial-admin.yaml"
    overlays:
      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"
