---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.labels["heritage"]
      - metadata.labels["release"]
      - metadata.labels["chart"]
    action: delete

yamlFiles:
  - name: "infisical config"
    path: "../../vendor/infisical.yaml"
    outputPath: "secrets/infisical/config.yaml"
    overlays:
      - name: "ensure we are only acting upon config resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Secret")]
              - query: $[?($.kind != "ConfigMap")]

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"

      - name: "remove the postgresql secret's randomly generated passwords"
        query: data
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind == "Secret")]
              - query: $[?($.metadata.name == "postgresql")]

      - name: "ensure the postgresql secret uses an obviously fake password"
        query: stringData
        action: merge
        value:
          postgres-password: "thisisinsecure"
          password: "thisisinsecure"
        onMissing:
          action: inject
        documentQuery:
          - conditions:
              - query: $[?($.kind == "Secret")]
              - query: $[?($.metadata.name == "postgresql")]

      - name: "remove the redis secret's randomly generated password"
        query: data
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind == "Secret")]
              - query: $[?($.metadata.name == "redis")]

      - name: "ensure the redis secret uses an obviously fake password"
        query: stringData
        action: merge
        value:
          redis-password: "thisisinsecure"
        onMissing:
          action: inject
        documentQuery:
          - conditions:
              - query: $[?($.kind == "Secret")]
              - query: $[?($.metadata.name == "redis")]
