---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "apply nukleros labels to pod template"
    query: "spec.template.metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.labels["heritage"]
      - metadata.labels["release"]
      - metadata.labels["chart"]
    action: delete

yamlFiles:
  - name: "infisical bootstrap job"
    path: "../../vendor/infisical.yaml"
    outputPath: "secrets/infisical/job.yaml"
    overlays:
      - name: "ensure we are only acting upon job resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Job")]

      - name: "ensure namespace is updated"
        query: metadata
        action: merge
        value:
          namespace: "{{ .namespace }}"

      - name: "remove the helm hook annotations, since this is not applied via helm"
        query: metadata.annotations
        action: delete

      - name: "ensure the job uses the renamed service account"
        query: spec.template.spec.serviceAccountName
        action: replace
        value: "infisical"

      - name: "ensure the job runs on linux nodes"
        query: spec.template.spec
        action: merge
        value:
          nodeSelector:
            kubernetes.io/os: linux
