---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query:
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.labels["heritage"]
      - metadata.labels["release"]
      - metadata.labels["chart"]
    action: delete

yamlFiles:
  - name: "infisical services"
    path: "../../vendor/infisical.yaml"
    outputPath: "secrets/infisical/service.yaml"
    overlays:
      - name: "ensure we are only acting upon service resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Service")]

      - name: "ensure namespace is updated"
        query: metadata
        action: merge
        value:
          namespace: "{{ .namespace }}"

      - name: "prefix the infisical service's component/app labels with app.kubernetes.io"
        query: metadata.labels
        action: merge
        value:
          app.kubernetes.io/component: infisical
          app.kubernetes.io/app: infisical-standalone
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "infisical")]

      - name: "remove the infisical service's unprefixed component/app labels"
        query:
          - metadata.labels.component
          - metadata.labels.app
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "infisical")]

      - name: "prefix the infisical service selector's component/app/release labels with app.kubernetes.io"
        query: spec.selector
        action: merge
        value:
          app.kubernetes.io/component: infisical
          app.kubernetes.io/app: infisical-standalone
          app.kubernetes.io/release: infisical
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "infisical")]

      - name: "remove the infisical service selector's unprefixed component/app/release labels"
        query:
          - spec.selector.component
          - spec.selector.app
          - spec.selector.release
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.metadata.name == "infisical")]
