---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      app: "{{ .project }}"
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
      app.kubernetes.io/name: "{{ .project }}"
      app.kubernetes.io/instance: "{{ .project }}"
      app.kubernetes.io/component: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query: 
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
      - spec.template.metadata.labels["helm.sh/chart"]
      - spec.template.metadata.labels["app.kubernetes.io/managed-by"]
      - metadata.annotations["helm.sh/resource-policy"]
    action: delete

  - name: "set the name to prefix with aws"
    query: metadata.name
    value: "{{ .project }}"
    action: replace

yamlFiles:
  - name: "aws-pod-identity-webhook rbac"
    path: "../../vendor/auth.yaml"
    outputPath: "identity/aws-pod-identity-webhook/rbac.yaml"
    overlays:
      - name: "ensure we are only acting upon rbac resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ServiceAccount")]
              - query: $[?($.kind != "Role")]
              - query: $[?($.kind != "RoleBinding")]
              - query: $[?($.kind != "ClusterRole")]
              - query: $[?($.kind != "ClusterRoleBinding")]

      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "{{ .namespace }}"

      - name: "ensure name is updated"
        query:
          - roleRef.name
          - subjects[*].name
        value: "{{ .project }}"
