---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-bootstrap-credentials
  namespace: secrets-system
type: Opaque
stringData:
  INFISICAL_ADMIN_EMAIL: "admin@example.com"
  INFISICAL_ADMIN_PASSWORD: "thisisinsecure"
