---
project: cert-manager
replicas: 2
injector:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      memory: "128Mi"
controller:
  replicas: 2
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      memory: "64Mi"
webhook:
  replicas: 2
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      memory: "64Mi"
