---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "kong secret"
    path: "../../vendor/all-in-one-dbless-k4k8s-enterprise.yaml"
    outputPath: "ingress/kong/secret.yaml"
    overlays:
      - name: "ensure we are only acting upon secrets"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Secret")]

      - name: "ensure creation timestamp is missing"
        query: metadata.creationTimestamp
        action: delete

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"
