---
commonOverlays: []
yamlFiles:
  - name: "kong services"
    path: "../../vendor/all-in-one-dbless-k4k8s-enterprise.yaml"
    outputPath: "ingress/kong/service.yaml"
    overlays:
      - name: "ensure we are only acting upon services"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Service")]

      - name: "ensure creation timestamp is missing"
        query: metadata.creationTimestamp
        action: delete

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"

      - name: "add kubernetes and nukleros labels"
        query: "metadata"
        value:
          labels:
            app.kubernetes.io/name: ingress-kong
            app.kubernetes.io/instance: ingress-kong
            app.kubernetes.io/component: ingress-kong
            app.kubernetes.io/version: {{ .version }}
            app.kubernetes.io/part-of: kong-ingress-controller
            app.kubernetes.io/managed-by: platform-component-library
            platform.nukleros.io/group: ingress
            platform.nukleros.io/project: kong

