---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "nginx custom resource definitions"
    path: "../../vendor/common/crds"
    outputPath: "ingress/nginx"

