---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

yamlFiles:
  - name: "nginx service account"
    path: "../../vendor/common/ns-and-sa.yaml"
    outputPath: "ingress/nginx/rbac.yaml"
    overlays:
      - name: "ensure we are only acting upon service account resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ServiceAccount")]

  - name: "nginx cluster role"
    path: "../../vendor/rbac/rbac.yaml"
    outputPath: "ingress/nginx/rbac.yaml"
    overlays:
      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "{{ .namespace }}"

      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "{{ .namespace }}"


