---
commonOverlays: []
yamlFiles:
  - name: "nginx default server cert secret"
    path: "../../vendor/common/default-server-secret.yaml"
    outputPath: "ingress/nginx/secret.yaml"
    overlays:
      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"

