---
commonOverlays:
  - name: "apply nukleros labels"
    query: "metadata.labels"
    value:
      platform.nukleros.io/category: "{{ .category }}"
      platform.nukleros.io/project: "{{ .project }}"
    onMissing:
      action: inject

  - name: "remove the helm info"
    query: 
      - metadata.labels["helm.sh/chart"]
      - metadata.labels["app.kubernetes.io/managed-by"]
    action: delete

yamlFiles:
  - name: "external-secrets webhooks"
    path: "../../vendor/external-secrets.yaml"
    outputPath: "secrets/external-secrets/webhook.yaml"
    overlays:
      - name: "ensure we are only acting upon webhook resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ValidatingWebhookConfiguration")]
              - query: $[?($.kind != "MutatingWebhookConfiguration")]

      - name: "ensure namespace is updated"
        query:
          - metadata.namespace
          - webhooks[*].clientConfig.service.namespace
        value: "{{ .namespace }}"
