---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-bootstrap-credentials
  namespace: nukleros-secrets-system
  labels:
    platform.nukleros.io/category: secrets
    platform.nukleros.io/project: infisical
type: Opaque
stringData:
  INFISICAL_ADMIN_EMAIL: admin@example.com
  INFISICAL_ADMIN_PASSWORD: thisisinsecure
